// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqnzwljetuauwmbldhsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impxbnp3bGpldHVhdXdtYmxkaHN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3MzI5MTcsImV4cCI6MjA1NjMwODkxN30.R5ph1CuXEyoQTxIc6SFvStwjXMxX0wK9zTYdf71BhrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);